##start with a base image containing java runtime
#FROM openjdk:26-ea-21-jdk-bookworm
#
#
##information about who maintains the image
#MAINTAINER lobiq.xyz
#
##Add the application's jar to the image
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
#
##Execute the application
#ENTRYPOINT ["java", "-jar", "accounts-0.0.1-SNAPSHOT.jar"]