services:
  accounts:
    image: "artwh0/accounts:v1"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - bank
  cards:
    image: "artwh0/cards:v1"
    container_name: "cards-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - bank
  loans:
    image: "artwh0/loans:v1"
    container_name: "loans-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - bank
networks:
  bank:
    driver: "bridge"