
build:
  version: "3.0"

accounts:
  message: "Welcome to Cards Service"
  contactDetails:
    name: "Anik"
    email: "aniksust052@gmail.com"
    phone: "1234567890"
  onCallSupport:
    - (+88)1234567890
    - (+88)1234567890


