
build:
  version: "1.0"

loans:
  message: "Welcome to Loans Service PROD apis"
  contactDetails:
    name: "Anik"
    email: "artwh052@gmail.com"
    phone: "1234567890"
  onCallSupport:
    - (+88)1234567890
    - (+88)1234567890